[package]
name = "pywasmi"
version = "0.6.0"
authors = ["Kai Strempel <kstrempel@gmail.com>"]

[dependencies]
wasmi = "0.4.2"

[dependencies.pyo3]
version = "0.5.2"
features = ["extension-module"]

[lib]
name = "pywasmi"
crate-type = ["cdylib"]
